### PR TITLE
Add subnational boundaries

### LINKED ISSUE #233: [HURUmap] Add subnational Boundaries
## Description
Add subnational boundary data for the first phase Takwimu countries

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Source boundaries data
- [ ] Add `geoid`, `name`, `level` and  `code` to the properties

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Added one level of subnational boundaries

Fixes #233 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
screencapture-localhost-8000-profiles-level1-sn_1_012-tambacounda-2018-07-24-12_10_32

screencapture-localhost-8000-profiles-level1-ng_1_012-edo-2018-07-24-12_09_03

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**The geography files are getting heavier, load time is increasing**

### CODE REVIEW

**Comment by kilemensi** [comment]
@phillipahereza 

When you click on a country, the url, `http://localhost:8000/profiles/country-TZ/` **404**s
When you manually edit the url to how it currently was, `http://localhost:8000/profiles/country-TZA-tanzania/`, it loads but the map doesn't show.

screenshot from 2018-07-24 15-27-57

**Comment by phillipahereza** [comment]
@kilemensi have you load the `wazimap_geographies.sql` table afresh? We changed a few things in there

**Comment by kilemensi** [comment]
Reloading does help @phillipahereza but I can't access subnational level. Is this the slow part you were talking about?

screenshot from 2018-07-24 15-50-50

**Comment by phillipahereza** [comment]
@kilemensi that's strange, could you check your console to see if there are any js errors from loading the geometry data

**Comment by kilemensi** [comment]
```
[24/Jul/2018 15:49:23] "GET /static/js/affix.js HTTP/1.1" 404 1747
[24/Jul/2018 15:49:23] "GET /static/js/profiles.js HTTP/1.1" 404 1756
[24/Jul/2018 15:49:23] "GET /static/js/affix.js HTTP/1.1" 404 1747
[24/Jul/2018 15:49:23] "GET /static/js/profiles.js HTTP/1.1" 404 1756
[24/Jul/2018 15:49:23] "GET /static/js/affix.js HTTP/1.1" 404 1747
[24/Jul/2018 15:49:23] "GET /static/js/profiles.js HTTP/1.1" 404 1756

```

**Comment by phillipahereza** [comment]
@kilemensi I meant browser console

**Comment by phillipahereza** [comment]
@tebajanga could you try running this on your machine

**Comment by kilemensi** [comment]
Chrome console @phillipahereza 

screenshot from 2018-07-24 16-03-51

**Comment by kilemensi** [comment]
Finally

screenshot from 2018-07-24 16-57-34

LGTM @phillipahereza

**Pull request merged**
