### PR TITLE
Multiple Widgets per Indicator

### LINKED ISSUE #371: Multiple Widgets per Indicator
**Is your feature request related to a problem? Please describe.**
It's currently impossible to have more than one widget per indicator. By widget, we mean a viz, an embed, a document, etc. Hence it's impossible to have "multiple views" of the same indicator data.

**Describe the solution you'd like**
For each indicator, one should be able to add more than one widget.

**Describe alternatives you've considered**

 * [ ] Convert the current `IndicatorsBlock` into `IndicatorWidgetsBlock`,
 * [ ] Create a new `IndicatorBlock` to contain `IndicatorWidgetsBlock`, and
 * [ ] Modify `TopicBlock` to contain the new `IndicatorBlock` instead of the old `IndicatorsBlock`.

**Additional context**
The new indicator should:

 * [ ] Contain a way of indicating which widget is the main Visual widget or primary widget that would be displayed by default, and
 * [ ] Allow lazy loading of heavy widgets like documents (if possible).

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Feature to enable adding multiple widgets per indicator

### To run the data migrations
```
python manage.py migrate takwimu indicator_migrations
```

Fixes #371

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots
multiple

screencapture-localhost-8000-profiles-senegal-2018-09-14-01_13_09

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Hey @phillipahereza.

I've been playing with this today and it looks good (just minor things we can patch up before merging), but I just got to ask before pulling the trigger:

What if we add versions and keep `indications` name the same in the `TopicBlock`? This means when we're doing migration up, we'll check if there is `versions` field in `topic['value']`. If not, then we know we need to migrate it to multiple widget and we include `'version': 'v2'` in the new `topic['value']`.
This means even in the future if there are new requirements, we can just change the `versons` again without having to keep changing name field names.

What do you think?

**Comment by phillipahereza** [comment]
@kilemensi you mean instead of something like `indicator_group` we keep it as `indicators` and add the `version` flag to show that this was changed?

**Comment by kilemensi** [comment]
> @kilemensi you mean instead of something like `indicator_group` we keep it as `indicators` and add the `version` flag to show that this was changed?

Exactly.

**Comment by phillipahereza** [comment]
@kilemensi so how do we represent the 'container' which can hold multiple related indicators?

**Comment by kilemensi** [comment]
You have already implemented the container in the `IndicatorsBlock` (and `IndicatorWidgetBlock`) @phillipahereza. I'm talking about not changing the `TopicBlock` `indicators` field to `indicator_groups` just so that we know there has been a change.

**Comment by phillipahereza** [comment]
screen shot 2018-09-14 at 16 09 19
@kilemensi this is what the structure looks like at the moment, if we replace `indicator_groups` with `indicators`, you see we already have an `indicators` object nested  inside there? Will it be ok to have 2 'things' labeled `indicators`?

**Comment by kilemensi** [comment]
We **replace** the original `indicators` @phillipahereza. I mean we are reconstructing the whole object as `raw_text` before saving so replacing it should be fine I think. Something like:

```python
def indicators_to_indicator_groups(topic):
    indicators = []
    if no topic['value']['version']:
        current_indicators = topic['value'].get('indicators', []):
        for indicator in current_indicators:
            indicators.append({
                'type': 'indicators',
                'id': str(uuid.uuid1()),
                'value': {
                    'title': indicator['value']['title'],
                    'indicators': [current_indicator],
                    'version': 'v2',
                }
            })
        # REPLACE indicators here
        topic['value']['indicators'] = indicators
    return topic
```

**Comment by kilemensi** [comment]
I've added the :point_up: fix @phillipahereza & I think it works. Test it when you get the chance.

**Comment by phillipahereza** [comment]
@kilemensi Cool, now I understand, I was getting confused by `indicator` and `indicators`

**Comment by kilemensi** [comment]
Just one issue with this PR @phillipahereza , I can't see the multiple widgets in the _dashboard_ **for existing** indicators. Can you confirm if they're visible and editable?

**Comment by phillipahereza** [comment]
@kilemensi the existing indicators only had one indicator so one widget is created for them and that is working fine on my side. Adding another widget to an existing indicator also works as expected

**Comment by kilemensi** [comment]
When you get the chance @DavidLemayian, can you try this PR before we merge? It's a big change and I'd like to make sure it covers all the corner cases.

**Comment by kilemensi** [comment]
> @kilemensi the existing indicators only had one indicator so one widget is created for them and that is working fine on my side. Adding another widget to an existing indicator also works as expected

Cool @phillipahereza. So you don't get blank indicators for say Nigeria profile page (in the dashboard)?

**Comment by DavidLemayian** [comment]
@kilemensi Could we add ability to customise the widget label (on the tab nav)?

**Comment by kilemensi** [comment]
> @kilemensi Could we add ability to customise the widget label (on the tab nav)?

Done @DavidLemayian

**Pull request merged**
