### PR TITLE
Adding demographics at National and SubNational Levels

### PR DESCRIPTION
**Pull request by tebajanga**
## Description

Uploading and showing HURUmap demographics data at National and Sub national Levels.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

#### Country Tanzania
demographics

#### Level1 Dakar - Senegal
dakar_population

#### Level1 Dodoma - Tanzania
dodoma_population

#### Level1 Lagos - Nigeria
lagos_population

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by tebajanga** [comment]
Okay @kilemensi , I will remove the unnecessary code.

**Comment by tebajanga** [comment]
@kilemensi  and @phillipahereza , I added population data at subnationial level.

**Comment by tebajanga** [comment]
@phillipahereza , the `geo_code` for **Njombe** region is now `TZ_1_21` , should we change it to `TZ_1_021` to match other geo_codes format?

**Comment by kilemensi** [comment]
Yeah @tebajanga, standardize all `geo_code`s so that there are no surprises from here on.

**Comment by phillipahereza** [comment]
@tebajanga I hope the code has been updated in all the places it appears?

**Comment by tebajanga** [comment]
Yes @phillipahereza , I updated in all places it appears. cc @kilemensi

**Pull request merged**
