### PR TITLE
[Staging] Analysis page content with indicators

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Update frontend to take advantage of the new **freeform** backend analysis page design.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screenshot_2019-04-26 Takwimu

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by karimkawambwa** [comment]
@kilemensi can you review this, I am still trying to get download to work for the different visuals

**Comment by kilemensi** [comment]
@karimkawambwa looks good :+1: .

Just to confirm:
 i. Profiles have summaries that should come before the first text component. Seems like we've missed it. Can you confirm and add it if true,
 ii. Have you considered loading each content **when** it's clicked in the table of content nav. Now that we have viz, loading all contents in one go is starting to feel a bit heavy, and
 iii. Most viz that use `<div>` and not `<iframe>` do not load. Is this something `react` specific?

--------------------------

RE: Downloading other non-HURUmap viz. We went down this way and it seemed like a lost cause for most of them since the iframe comes from a different server.

**Comment by karimkawambwa** [comment]
> Profiles have summaries that should come before the first text component. Seems like we've missed it. Can you confirm and add it if true,

Dont think summary exists.
I could not find anything like that.

> ii. Have you considered loading each content when it's clicked in the table of content nav. Now that we have viz, loading all contents in one go is starting to feel a bit heavy, and

I am not sure what you mean by this but it should only load on mount.

> iii. Most viz that use <div> and not <iframe> do not load. Is this something react specific?

I was not sure, I don't think it is react but I will give it a try a gain, maybe the flourish script is not loading.

**Comment by kilemensi** [comment]
Summaries do exist @karimkawambwa:

Screenshot from 2019-04-25 19-02-00

On the loading issue, I meant we're currently loading **all** content (profile and it's profile sections) when the component mounts. I was suggesting loading section by section. Load all section titles on the first load so we can populate the table of content and then load a given section body when that section title is clicked in the table of content...

**Comment by kilemensi** [comment]
Lets create stories for the pending issues @karimkawambwa and fix them on separate PR(s). I'll go ahead and merge this PR and deploy to staging for :eyes:

**Comment by karimkawambwa** [comment]
> Summaries do exist @karimkawambwa:
> 
> Screenshot from 2019-04-25 19-02-00
> 
> On the loading issue, I meant we're currently loading **all** content (profile and it's profile sections) when the component mounts. I was suggesting loading section by section. Load all section titles on the first load so we can populate the table of content and then load a given section body when that section title is clicked in the table of content...

You are right, I probably looked at the wrong response.
Most likely ProfileSectionPage response :/

**Pull request merged**
