### PR TITLE
[Staging] Hurumap Actions

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Action buttons (download, share etc...)

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screen Shot 2019-05-07 at 2 09 24 PM

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Need to be something like this @karimkawambwa:

Screenshot_2019-05-07 Zeplin - Project

We may choose to do the summary and button on a different PR but the styling (especially the background and actions position/alignment) need to match this design.

**Comment by nerdlet** [comment]
@karimkawambwa Looks good to me..noticed though there is some misalignment on the column layouts. Maybe look into that

image

**Comment by nerdlet** [comment]
@karimkawambwa Also maybe a mention, noticed this from the console
image

**Comment by karimkawambwa** [comment]
@nerdlet thanks for the pointers. 

Theses will change to match the new designs.

**Comment by karimkawambwa** [comment]
@kilemensi here are the visual elements

For checking if the visual is in an analysis, I will do this in a seperate PR. 
I have been exploring the options of adding endpoint to get visuals wagtail and indicate which analysis they are from.

**Comment by kilemensi** [comment]
Screenshot_2019-05-07 Takwimu profile South Africa

The embed dialog is a bit off @karimkawambwa

**Comment by karimkawambwa** [comment]
> Only when I open developer tools (both in chrome and FF) that's when the charts are rendered:

I started running into this towards the end of the day.
Something to look into tomorrow.

**Comment by karimkawambwa** [comment]
@phillipahereza could you help debug d3 issue here

**Pull request merged**
