### PR TITLE
Fix profile content

### LINKED ISSUE #220: [BUG] Fix profile contents styling
## Description
- [x] Title 'Country profile contents' is too big
- [x] The section label eg. 'Section 1' are a tad too big
- [x] The font weight of the body text needs to match the lighter font weight used in the design
- [x] The grey BG highlight on the current section is too dark
- [x] Ideally only the section title would underline on mouse hover

## Screenshots
screen shot 2018-07-22 at 00 42 19

### PR DESCRIPTION
**Pull request by mtuchi**
## Description

Fixes #220, #256 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
profile-content

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by mtuchi** [comment]
@DavidLemayian don't merge yet, there are 3 task remain for this PR

**Comment by DavidLemayian** [comment]
@mtuchi Cool. Added label to title. Change it once ready for review.

**Comment by mtuchi** [comment]
@DavidLemayian one task remain, you can just review what i have so far

**Comment by DavidLemayian** [comment]
@mtuchi Looks good so far.

**Comment by mtuchi** [comment]
@DavidLemayian converted the pending task into github issue, this PR is ready for review and merge

**Comment by mtuchi** [comment]
@DavidLemayian fixed related issue and updated screenshot as well

**Pull request merged**
