### PR TITLE
Hotfix/data kenya v2

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Data Added
- Programmes funded by Donors
- Health Centre distribution
- Government expenditure on social issues

## Type of change

- [x] Data

## Screenshots
screencapture-localhost-8000-profiles-country-ke-kenya-2018-09-20-15_36_24

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Amount is 0 on **Principle Donors Contribution** @phillipahereza e.g. *Donor Contributions (000,000 of USD)* on*

**Comment by phillipahereza** [comment]
@kilemensi that's inherent from Wazimap, it keeps rounding downwards, don't know why though but I am looking for a fix

**Comment by kilemensi** [comment]
> @kilemensi that's inherent from Wazimap, it keeps rounding downwards, don't know why though but I am looking for a fix

Cool. Can I remove them for now and push the data (you'll create a separate issue to track the fix)?

**Comment by phillipahereza** [comment]
> > @kilemensi that's inherent from Wazimap, it keeps rounding downwards, don't know why though but I am looking for a fix
> 
> Cool. Can I remove them for now and push the data (you'll create a separate issue to track the fix)?
You can remove them

**Pull request merged**
