### PR TITLE
Open Zendesk Ticket from Enquiry Form

### LINKED ISSUE #204: [BUG] Link Support Services Enquiry Form to Zendesk
## Description
Create zendesk tickets from inquiry form on the services page

## Screenshots
skitch-1

## Tasks

- [ ] Form submit to Zendesk URL?
- [ ] ?

### PR DESCRIPTION
**Pull request by phillipahereza**
## Description

Connect form to Zendesk - create a ticket after the inquiry form has been submitted

Fixes #204 )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Screenshots
support
screen shot 2018-07-28 at 12 03 27

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by phillipahereza** [comment]
@DavidLemayian fixed

**Comment by phillipahereza** [comment]
@DavidLemayian not much setting up needed, only need to generate an API Token

**Comment by DavidLemayian** [comment]
@phillipahereza For the previous implementation to work, you must have set some very dangerous options on Zendesk e.g to allow anyone to open a ticket without having a verified e-mail. Unless I misunderstood what you did?

**Comment by phillipahereza** [comment]
@DavidLemayian nope I didn't change anything, Zendesk has an open API for requests. Works out of the box

**Comment by DavidLemayian** [comment]
@phillipahereza Cool. If not changed by you then it'll be on comms team to decide - https://developer.zendesk.com/rest_api/docs/core/requests#anonymous-requests

**Comment by DavidLemayian** [comment]
@kilemensi It's all you now.

**Pull request merged**
