### PR TITLE
[Staging] Search

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Implement Search UI.
The custom scroll will not work on Firefox.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screen Shot 2019-04-17 at 10 12 49 AM

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by karimkawambwa** [comment]
@kilemensi @nerdlet 👀

**Comment by karimkawambwa** [comment]
> Screenshot from 2019-04-29 16-16-02

Can't reproduce this in firefox

**Comment by karimkawambwa** [comment]
@nerdlet were you able to reproduce what @kilemensi saw ^

**Comment by nerdlet** [comment]
@karimkawambwa So nope, The only difference I noticed was the scroll fades once you start searching, plus the color is more grey than white

**Comment by KhadijaMahanga** [comment]
Screenshot from 2019-04-30 17-19-16

@karimkawambwa @nerdlet I tried to reproduce and saw that on firefox ^^ on firefox.

Pushed fixes, it was a scrollbar for an empty menulist (search suggestion)

**Pull request merged**
