### PR TITLE
Style TOC profile

### LINKED ISSUE #221: [BUG] Fix Profile TOC
## Description
Don't mind some of your styling changes on this menu, but could you please update the following:

## Screenshots
screen shot 2018-07-22 at 00 49 33

## Tasks

- [x] Color and size of Nigerian flag to match design
- [x] Color of country drop down should not be that blue.
- [x]  Please increase font weight of section titles (and reduce the font weight of the sub-section links)
- [x]  Please update the + and – icons to match the design
- [x]  Please collapse all accordions by default (bar the first section - this is to indicate behaviour to the user.

### PR DESCRIPTION
**Pull request by mtuchi**
## Description

Increase font weight of section titles (and reduce the font weight of the sub-section links), update the + and – icons to match the design, collapse all accordions by default (bar the first section - this is to indicate behavior to the user.

Fixes #221 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
toc

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by mtuchi** [comment]
@DavidLemayian can you review again the PR, i have pushed some updates

**Comment by DavidLemayian** [comment]
@mtuchi Screenshot update needed.

**Comment by mtuchi** [comment]
@DavidLemayian  regarding this :point_down: 
`Please make "CLOSE" button font-weight heavy`
The font-weight was `bold` you requested to be `light` 
Should i change back to `bold`

**Comment by DavidLemayian** [comment]
@mtuchi Kizungu ngumu clearly. 😂  Please ask @KhadijaMahanga to translate:

> That "CLOSE" button is looking a little light.. font-weight light. :)

**Comment by DavidLemayian** [comment]
Just for clarity - should be heavy/bold.

**Pull request merged**
