### PR TITLE
[Staging] PDF Document Indicator to download document

### PR DESCRIPTION
**Pull request by karimkawambwa**
## Description

Implement download for PDF Document.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshoot

Screen Shot 2019-05-27 at 4 02 51 PM

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by karimkawambwa** [comment]
@kilemensi

**Comment by kilemensi** [comment]
Running it on local @karimkawambwa and this is the document URL I get for a document I just uploaded:  http://dev.takwimu.africa/documents/157/XXXXX.pdf where `XXXXXXX` is the document name.

Where does `dev.takwimu.africa` comes from and isn't this going to bite us again?

**Comment by phillipahereza** [comment]
@kilemensi  I think I fixed the `dev.takwimu.africa` thing [here](https://github.com/CodeForAfrica/HURUmap/commit/a820b1364663d0e836d8f902132adb9268460f84)

**Comment by kilemensi** [comment]
> @kilemensi I think I fixed the `dev.takwimu.africa` thing [here](https://github.com/CodeForAfrica/HURUmap/commit/a820b1364663d0e836d8f902132adb9268460f84)

So merging @staging to this should fix it @phillipahereza?

**Comment by karimkawambwa** [comment]
@kilemensi you gotta change some setting in the dashboard.

**Comment by kilemensi** [comment]
> @kilemensi you gotta change some setting in the dashboard.

Merging `staging` fixed it @karimkawambwa.

**Comment by karimkawambwa** [comment]
@kilemensi let me know if its all good then...

**Pull request merged**
