### PR TITLE
Add countries geo map icons

### PR DESCRIPTION
**Pull request by mtuchi**
## Description

Added static file for countries in profile page.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
screenshot_2018-09-19_13-35-07

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DavidLemayian** [comment]
Nice. How are you generating the SVGs? Do the boundaries match what we have in HURUmap for latest boundaries?

**Comment by mtuchi** [comment]
@DavidLemayian 
I have realized the title might have mislead you, It's the map icons for the countries section on profile page (Hurumap). See [zeplin](https://zpl.io/aMqJOYN) 

@kilemensi needed this for kenya geo map icon

**Comment by DavidLemayian** [comment]
@mtuchi To clarify- I'm wondering if the boundaries in the image are actually "current"? E.g in Kenya we moved from Provinces to Counties so the current SVG is not representative of today's Kenya. cc @kilemensi

**Comment by mtuchi** [comment]
@DavidLemayian 
Good question, currently i have pulled all the icons from [zeplin](https://zpl.io/aMqJOYN) designs, 
Will have to ask @seangp for help on getting the updated version

**Pull request merged**
